# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch
# Eww widget
exec-once = eww daemon
exec-once = eww open desktop_clock
exec-once = ~/.config/eww/desktop-note/start-notes.sh
